apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "tensorstuff.fullname" . }}-worker 
  labels:
    app: {{ template "tensorstuff.name" . }}-worker
    chart: {{ template "tensorstuff.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.workerReplicaCount }}
  selector:
    matchLabels:
      app: {{ template "tensorstuff.name" . }}-worker
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "tensorstuff.name" . }}-worker
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: API_BASE_URL
              value: "http://fruit.westus2.az.k8sdemo.io"
          volumeMounts:
            - mountPath: /app/assets/images
              name: fruitshare
      volumes: 
        - name: fruitshare
          azureFile:
            secretName: azure-secret
            shareName: fruit
            readOnly: false
            
